# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lirn/mjpgcamera-streamer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lirn/mjpgcamera-streamer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lirn/mjpgcamera-streamer/CMakeFiles /home/lirn/mjpgcamera-streamer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lirn/mjpgcamera-streamer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named camera-cream

# Build rule for target.
camera-cream: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 camera-cream
.PHONY : camera-cream

# fast build rule for target.
camera-cream/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/camera-cream.dir/build.make CMakeFiles/camera-cream.dir/build
.PHONY : camera-cream/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/camera-cream.dir/build.make CMakeFiles/camera-cream.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/camera-cream.dir/build.make CMakeFiles/camera-cream.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/camera-cream.dir/build.make CMakeFiles/camera-cream.dir/main.cpp.s
.PHONY : main.cpp.s

src/StreamManager.o: src/StreamManager.cpp.o
.PHONY : src/StreamManager.o

# target to build an object file
src/StreamManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/camera-cream.dir/build.make CMakeFiles/camera-cream.dir/src/StreamManager.cpp.o
.PHONY : src/StreamManager.cpp.o

src/StreamManager.i: src/StreamManager.cpp.i
.PHONY : src/StreamManager.i

# target to preprocess a source file
src/StreamManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/camera-cream.dir/build.make CMakeFiles/camera-cream.dir/src/StreamManager.cpp.i
.PHONY : src/StreamManager.cpp.i

src/StreamManager.s: src/StreamManager.cpp.s
.PHONY : src/StreamManager.s

# target to generate assembly for a file
src/StreamManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/camera-cream.dir/build.make CMakeFiles/camera-cream.dir/src/StreamManager.cpp.s
.PHONY : src/StreamManager.cpp.s

src/StreamServer.o: src/StreamServer.cpp.o
.PHONY : src/StreamServer.o

# target to build an object file
src/StreamServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/camera-cream.dir/build.make CMakeFiles/camera-cream.dir/src/StreamServer.cpp.o
.PHONY : src/StreamServer.cpp.o

src/StreamServer.i: src/StreamServer.cpp.i
.PHONY : src/StreamServer.i

# target to preprocess a source file
src/StreamServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/camera-cream.dir/build.make CMakeFiles/camera-cream.dir/src/StreamServer.cpp.i
.PHONY : src/StreamServer.cpp.i

src/StreamServer.s: src/StreamServer.cpp.s
.PHONY : src/StreamServer.s

# target to generate assembly for a file
src/StreamServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/camera-cream.dir/build.make CMakeFiles/camera-cream.dir/src/StreamServer.cpp.s
.PHONY : src/StreamServer.cpp.s

src/V4L2Camera.o: src/V4L2Camera.cpp.o
.PHONY : src/V4L2Camera.o

# target to build an object file
src/V4L2Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/camera-cream.dir/build.make CMakeFiles/camera-cream.dir/src/V4L2Camera.cpp.o
.PHONY : src/V4L2Camera.cpp.o

src/V4L2Camera.i: src/V4L2Camera.cpp.i
.PHONY : src/V4L2Camera.i

# target to preprocess a source file
src/V4L2Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/camera-cream.dir/build.make CMakeFiles/camera-cream.dir/src/V4L2Camera.cpp.i
.PHONY : src/V4L2Camera.cpp.i

src/V4L2Camera.s: src/V4L2Camera.cpp.s
.PHONY : src/V4L2Camera.s

# target to generate assembly for a file
src/V4L2Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/camera-cream.dir/build.make CMakeFiles/camera-cream.dir/src/V4L2Camera.cpp.s
.PHONY : src/V4L2Camera.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... camera-cream"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/StreamManager.o"
	@echo "... src/StreamManager.i"
	@echo "... src/StreamManager.s"
	@echo "... src/StreamServer.o"
	@echo "... src/StreamServer.i"
	@echo "... src/StreamServer.s"
	@echo "... src/V4L2Camera.o"
	@echo "... src/V4L2Camera.i"
	@echo "... src/V4L2Camera.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

